# Generated by Django 4.2.3 on 2023-07-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.userimage')),
                ('processTimestamp', models.DateTimeField()),
                ('numPothole', models.IntegerField()),
            ],
        ),
    ]
