# Generated by Django 4.2.3 on 2023-07-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imageannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationGoogle',
            fields=[
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.userimage')),
                ('streetNumber', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='longitude',
        ),
    ]
