# Generated by Django 4.2.3 on 2023-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_geolocationgoogle_remove_userimage_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotation',
            name='isAcknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
