# Generated by Django 4.2.3 on 2023-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_IMAGE_THRESHOLD', models.IntegerField(default=10)),
                ('MAP_MAXIMUM_ZOOM_LEVEL', models.IntegerField(default=16)),
                ('MAP_MINIMUM_ZOOM_LEVEL', models.IntegerField(default=6)),
                ('MAP_INITIAL_ZOOM_LEVEL', models.IntegerField(default=7)),
            ],
        ),
    ]
